# Setup
title:            ''
tagline:          'Santi Rodriguez'
url:              https://sgrodriguez.github.io/
baseurl:          ''
paginate:         2

# About and contact
author:
  name:           'Santiago Rodriguez'
  url:            https://www.linkedin.com/in/santiago-g-rodriguez-/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
